In [27]:
import numpy as np 


In [2]:
training_data = np.load("./data/trmd_trn_data.npy")
testing_data = np.load("./data/trmd_tst_data.npy")

print(training_data.shape)
print(testing_data.shape)

(871, 64, 15000)
(436, 64, 15000)


Annotate runs between 3 and 6

In [20]:
# print(training_data[2][:,0])
# training_data[2][:,0] = [3]
# print(training_data[2])
def map_annotations(data):
    for i in range(data.shape[0]):
        task_class = data[i][0][0]
        if task_class > 6 and task_class < 11:
            data[i][:,0] = [task_class-4] #Remap to tasks between 3 and 6
        elif task_class >= 11:
            data[i][:,0] = [task_class-8] #Remap to tasks between 3 and 6
    return data


In [21]:
print(training_data[5][:,0])
mpd_trn_data = map_annotations(training_data)
print(mpd_trn_data[5][:,0])


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [22]:
print(testing_data[5][:,0])
mpd_tst_data = map_annotations(testing_data)
print(mpd_tst_data[5][:,0])

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


In [26]:
# for i in range(mpd_trn_data.shape[0]):
#     print(mpd_trn_data[i][:,0])
np.save("./data/anntd_trn_data", mpd_trn_data)
np.save("./data/anntd_tst_data", mpd_tst_data)

In [28]:
data = np.load('./data/EEGData.npy')
print(data.shape)

(1308, 64, 15000)


In [34]:
print(data[1307])

[[   5. -191. -200. ...  165.  185.  168.]
 [   5. -193. -202. ...  165.  185.  168.]
 [   5. -191. -201. ...  157.  176.  157.]
 ...
 [   5. -280. -285. ...  234.  233.  225.]
 [   5.  -90.  -95. ...  114.  100.   92.]
 [   5. -149. -157. ...  108.  100.   93.]]


In [35]:
print(data[1])
trmd_data = data[1:1308,:,:]
print(trmd_data[0])

[[  5.  -6.   0. ...  22.  16.  26.]
 [  5.   4.   7. ...  20.  15.  20.]
 [  5.   5.   8. ...  19.  14.  19.]
 ...
 [  5.  -2. -16. ...  16.  25.  23.]
 [  5.  12.   1. ...  21.  29.  29.]
 [  5.  14.   3. ...   7.  11.   4.]]
[[  5.  -6.   0. ...  22.  16.  26.]
 [  5.   4.   7. ...  20.  15.  20.]
 [  5.   5.   8. ...  19.  14.  19.]
 ...
 [  5.  -2. -16. ...  16.  25.  23.]
 [  5.  12.   1. ...  21.  29.  29.]
 [  5.  14.   3. ...   7.  11.   4.]]


In [38]:
print(trmd_data[3])
mpd_data = map_annotations(trmd_data)
print(mpd_data[3])

[[  13.  -53.  -55. ...  -27.  -30.  -25.]
 [  13.  -41.  -43. ...  -25.  -30.  -24.]
 [  13.  -42.  -44. ...  -26.  -31.  -25.]
 ...
 [  13.    3.    7. ...   -1.    2.   21.]
 [  13. -129. -127. ...  -31.  -29.   -7.]
 [  13.  -43.  -42. ...  -21.  -23.   -8.]]
[[   5.  -53.  -55. ...  -27.  -30.  -25.]
 [   5.  -41.  -43. ...  -25.  -30.  -24.]
 [   5.  -42.  -44. ...  -26.  -31.  -25.]
 ...
 [   5.    3.    7. ...   -1.    2.   21.]
 [   5. -129. -127. ...  -31.  -29.   -7.]
 [   5.  -43.  -42. ...  -21.  -23.   -8.]]


In [ ]:
np.save('./data/anntd_data', mpd_data)